// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azurestack.iothub.implementation;

import com.azure.resourcemanager.azurestack.iothub.fluent.models.EndpointHealthDataInner;
import com.azure.resourcemanager.azurestack.iothub.models.EndpointHealthData;
import com.azure.resourcemanager.azurestack.iothub.models.EndpointHealthStatus;

public final class EndpointHealthDataImpl implements EndpointHealthData {
    private EndpointHealthDataInner innerObject;

    private final com.azure.resourcemanager.azurestack.iothub.IotHubManager serviceManager;

    EndpointHealthDataImpl(
        EndpointHealthDataInner innerObject, com.azure.resourcemanager.azurestack.iothub.IotHubManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String endpointId() {
        return this.innerModel().endpointId();
    }

    public EndpointHealthStatus healthStatus() {
        return this.innerModel().healthStatus();
    }

    public EndpointHealthDataInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.azurestack.iothub.IotHubManager manager() {
        return this.serviceManager;
    }
}
