// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azurestack.iothub.implementation;

import com.azure.resourcemanager.azurestack.iothub.fluent.models.TestAllRoutesResultInner;
import com.azure.resourcemanager.azurestack.iothub.models.MatchedRoute;
import com.azure.resourcemanager.azurestack.iothub.models.TestAllRoutesResult;
import java.util.Collections;
import java.util.List;

public final class TestAllRoutesResultImpl implements TestAllRoutesResult {
    private TestAllRoutesResultInner innerObject;

    private final com.azure.resourcemanager.azurestack.iothub.IotHubManager serviceManager;

    TestAllRoutesResultImpl(
        TestAllRoutesResultInner innerObject,
        com.azure.resourcemanager.azurestack.iothub.IotHubManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public List<MatchedRoute> routes() {
        List<MatchedRoute> inner = this.innerModel().routes();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public TestAllRoutesResultInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.azurestack.iothub.IotHubManager manager() {
        return this.serviceManager;
    }
}
