// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azurestack.eventhub.implementation;

import com.azure.resourcemanager.azurestack.eventhub.fluent.models.CheckNameAvailabilityResultInner;
import com.azure.resourcemanager.azurestack.eventhub.models.CheckNameAvailabilityResult;
import com.azure.resourcemanager.azurestack.eventhub.models.UnavailableReason;

public final class CheckNameAvailabilityResultImpl implements CheckNameAvailabilityResult {
    private CheckNameAvailabilityResultInner innerObject;

    private final com.azure.resourcemanager.azurestack.eventhub.EventHubsManager serviceManager;

    CheckNameAvailabilityResultImpl(
        CheckNameAvailabilityResultInner innerObject,
        com.azure.resourcemanager.azurestack.eventhub.EventHubsManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String message() {
        return this.innerModel().message();
    }

    public Boolean nameAvailable() {
        return this.innerModel().nameAvailable();
    }

    public UnavailableReason reason() {
        return this.innerModel().reason();
    }

    public CheckNameAvailabilityResultInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.azurestack.eventhub.EventHubsManager manager() {
        return this.serviceManager;
    }
}
