// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azurestack.eventhub.implementation;

import com.azure.resourcemanager.azurestack.eventhub.fluent.models.OperationInner;
import com.azure.resourcemanager.azurestack.eventhub.models.Operation;
import com.azure.resourcemanager.azurestack.eventhub.models.OperationDisplay;

public final class OperationImpl implements Operation {
    private OperationInner innerObject;

    private final com.azure.resourcemanager.azurestack.eventhub.EventHubsManager serviceManager;

    OperationImpl(
        OperationInner innerObject, com.azure.resourcemanager.azurestack.eventhub.EventHubsManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String name() {
        return this.innerModel().name();
    }

    public OperationDisplay display() {
        return this.innerModel().display();
    }

    public OperationInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.azurestack.eventhub.EventHubsManager manager() {
        return this.serviceManager;
    }
}
