// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.hybrid.resources.models;

import com.azure.resourcemanager.hybrid.resources.fluent.models.CheckResourceNameResultInner;

/** An immutable client-side representation of CheckResourceNameResult. */
public interface CheckResourceNameResult {
    /**
     * Gets the name property: Name of Resource.
     *
     * @return the name value.
     */
    String name();

    /**
     * Gets the type property: Type of Resource.
     *
     * @return the type value.
     */
    String type();

    /**
     * Gets the status property: Is the resource name Allowed or Reserved.
     *
     * @return the status value.
     */
    ResourceNameStatus status();

    /**
     * Gets the inner com.azure.resourcemanager.azurestack.resources.fluent.models.CheckResourceNameResultInner object.
     *
     * @return the inner object.
     */
    CheckResourceNameResultInner innerModel();
}
