// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.hybrid.network.implementation;

import com.azure.resourcemanager.hybrid.network.fluent.models.ConnectionSharedKeyInner;
import com.azure.resourcemanager.hybrid.network.models.ConnectionSharedKey;

public final class ConnectionSharedKeyImpl implements ConnectionSharedKey {
    private ConnectionSharedKeyInner innerObject;

    private final com.azure.resourcemanager.hybrid.network.NetworkManager serviceManager;

    ConnectionSharedKeyImpl(
        ConnectionSharedKeyInner innerObject,
        com.azure.resourcemanager.hybrid.network.NetworkManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String id() {
        return this.innerModel().id();
    }

    public String value() {
        return this.innerModel().value();
    }

    public ConnectionSharedKeyInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.hybrid.network.NetworkManager manager() {
        return this.serviceManager;
    }
}
