// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

/**
 * Package containing the service clients for ResourceManagementClient. All resource groups and resources exist within
 * subscriptions. These operation enable you get information about your subscriptions and tenants. A tenant is a
 * dedicated instance of Azure Active Directory (Azure AD) for your organization.
 */
package com.azure.resourcemanager.azurestack.resources.fluent;
