// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.hybrid.authorization.implementation;

import com.azure.core.http.rest.PagedIterable;
import com.azure.core.util.Context;
import com.azure.core.util.logging.ClientLogger;
import com.azure.resourcemanager.hybrid.authorization.fluent.ClassicAdministratorsClient;
import com.azure.resourcemanager.hybrid.authorization.fluent.models.ClassicAdministratorInner;
import com.azure.resourcemanager.hybrid.authorization.models.ClassicAdministrator;
import com.azure.resourcemanager.hybrid.authorization.models.ClassicAdministrators;
import com.fasterxml.jackson.annotation.JsonIgnore;

public final class ClassicAdministratorsImpl implements ClassicAdministrators {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(ClassicAdministratorsImpl.class);

    private final ClassicAdministratorsClient innerClient;

    private final com.azure.resourcemanager.hybrid.authorization.AuthorizationManager serviceManager;

    public ClassicAdministratorsImpl(
        ClassicAdministratorsClient innerClient,
        com.azure.resourcemanager.hybrid.authorization.AuthorizationManager serviceManager) {
        this.innerClient = innerClient;
        this.serviceManager = serviceManager;
    }

    public PagedIterable<ClassicAdministrator> list() {
        PagedIterable<ClassicAdministratorInner> inner = this.serviceClient().list();
        return Utils.mapPage(inner, inner1 -> new ClassicAdministratorImpl(inner1, this.manager()));
    }

    public PagedIterable<ClassicAdministrator> list(Context context) {
        PagedIterable<ClassicAdministratorInner> inner = this.serviceClient().list(context);
        return Utils.mapPage(inner, inner1 -> new ClassicAdministratorImpl(inner1, this.manager()));
    }

    private ClassicAdministratorsClient serviceClient() {
        return this.innerClient;
    }

    private com.azure.resourcemanager.hybrid.authorization.AuthorizationManager manager() {
        return this.serviceManager;
    }
}
