// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.hybrid.authorization.implementation;

import com.azure.resourcemanager.hybrid.authorization.fluent.models.PolicyDefinitionInner;
import com.azure.resourcemanager.hybrid.authorization.models.PolicyDefinition;
import com.azure.resourcemanager.hybrid.authorization.models.PolicyMode;
import com.azure.resourcemanager.hybrid.authorization.models.PolicyType;

public final class PolicyDefinitionImpl implements PolicyDefinition {
    private PolicyDefinitionInner innerObject;

    private final com.azure.resourcemanager.hybrid.authorization.AuthorizationManager serviceManager;

    PolicyDefinitionImpl(
        PolicyDefinitionInner innerObject,
        com.azure.resourcemanager.hybrid.authorization.AuthorizationManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String id() {
        return this.innerModel().id();
    }

    public String name() {
        return this.innerModel().name();
    }

    public PolicyType policyType() {
        return this.innerModel().policyType();
    }

    public PolicyMode mode() {
        return this.innerModel().mode();
    }

    public String displayName() {
        return this.innerModel().displayName();
    }

    public String description() {
        return this.innerModel().description();
    }

    public Object policyRule() {
        return this.innerModel().policyRule();
    }

    public Object metadata() {
        return this.innerModel().metadata();
    }

    public Object parameters() {
        return this.innerModel().parameters();
    }

    public PolicyDefinitionInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.hybrid.authorization.AuthorizationManager manager() {
        return this.serviceManager;
    }
}
