// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.hybrid.compute.implementation;

import com.azure.resourcemanager.hybrid.compute.fluent.models.AccessUriInner;
import com.azure.resourcemanager.hybrid.compute.models.AccessUri;

public final class AccessUriImpl implements AccessUri {
    private AccessUriInner innerObject;

    private final com.azure.resourcemanager.hybrid.compute.ComputeManager serviceManager;

    AccessUriImpl(
        AccessUriInner innerObject, com.azure.resourcemanager.hybrid.compute.ComputeManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String accessSas() {
        return this.innerModel().accessSas();
    }

    public AccessUriInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.hybrid.compute.ComputeManager manager() {
        return this.serviceManager;
    }
}
