// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.hybrid.appservice.implementation;

import com.azure.resourcemanager.hybrid.appservice.fluent.models.ApplicationStackInner;
import com.azure.resourcemanager.hybrid.appservice.models.ApplicationStack;
import com.azure.resourcemanager.hybrid.appservice.models.StackMajorVersion;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

public final class ApplicationStackImpl implements ApplicationStack {
    private ApplicationStackInner innerObject;

    private final com.azure.resourcemanager.hybrid.appservice.AppServiceManager serviceManager;

    ApplicationStackImpl(
        ApplicationStackInner innerObject, com.azure.resourcemanager.hybrid.appservice.AppServiceManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String name() {
        return this.innerModel().name();
    }

    public String display() {
        return this.innerModel().display();
    }

    public String dependency() {
        return this.innerModel().dependency();
    }

    public List<StackMajorVersion> majorVersions() {
        List<StackMajorVersion> inner = this.innerModel().majorVersions();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public List<ApplicationStack> frameworks() {
        List<ApplicationStackInner> inner = this.innerModel().frameworks();
        if (inner != null) {
            return Collections
                .unmodifiableList(
                    inner
                        .stream()
                        .map(inner1 -> new ApplicationStackImpl(inner1, this.manager()))
                        .collect(Collectors.toList()));
        } else {
            return Collections.emptyList();
        }
    }

    public ApplicationStackInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.hybrid.appservice.AppServiceManager manager() {
        return this.serviceManager;
    }
}
