// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.hybrid.appservice.implementation;

import com.azure.resourcemanager.hybrid.appservice.fluent.models.MSDeployLogInner;
import com.azure.resourcemanager.hybrid.appservice.models.MSDeployLog;
import com.azure.resourcemanager.hybrid.appservice.models.MSDeployLogEntry;
import java.util.Collections;
import java.util.List;

public final class MSDeployLogImpl implements MSDeployLog {
    private MSDeployLogInner innerObject;

    private final com.azure.resourcemanager.hybrid.appservice.AppServiceManager serviceManager;

    MSDeployLogImpl(
        MSDeployLogInner innerObject, com.azure.resourcemanager.hybrid.appservice.AppServiceManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String id() {
        return this.innerModel().id();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String type() {
        return this.innerModel().type();
    }

    public String kind() {
        return this.innerModel().kind();
    }

    public List<MSDeployLogEntry> entries() {
        List<MSDeployLogEntry> inner = this.innerModel().entries();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public MSDeployLogInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.hybrid.appservice.AppServiceManager manager() {
        return this.serviceManager;
    }
}
