// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.hybrid.appservice.implementation;

import com.azure.resourcemanager.hybrid.appservice.fluent.models.ValidateResponseInner;
import com.azure.resourcemanager.hybrid.appservice.models.ValidateResponse;
import com.azure.resourcemanager.hybrid.appservice.models.ValidateResponseError;

public final class ValidateResponseImpl implements ValidateResponse {
    private ValidateResponseInner innerObject;

    private final com.azure.resourcemanager.hybrid.appservice.AppServiceManager serviceManager;

    ValidateResponseImpl(
        ValidateResponseInner innerObject, com.azure.resourcemanager.hybrid.appservice.AppServiceManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String status() {
        return this.innerModel().status();
    }

    public ValidateResponseError error() {
        return this.innerModel().error();
    }

    public ValidateResponseInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.hybrid.appservice.AppServiceManager manager() {
        return this.serviceManager;
    }
}
