// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azurestack.eventhubs.models;

import com.azure.resourcemanager.azurestack.eventhubs.fluent.models.EHNamespaceIdListResultInner;
import java.util.List;

/** An immutable client-side representation of EHNamespaceIdListResult. */
public interface EHNamespaceIdListResult {
    /**
     * Gets the value property: Result of the List Namespace IDs operation.
     *
     * @return the value value.
     */
    List<EHNamespaceIdContainer> value();

    /**
     * Gets the inner com.azure.resourcemanager.azurestack.eventhub.fluent.models.EHNamespaceIdListResultInner object.
     *
     * @return the inner object.
     */
    EHNamespaceIdListResultInner innerModel();
}
