// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azurestack.appservice.implementation;

import com.azure.resourcemanager.azurestack.appservice.fluent.models.MigrateMySqlStatusInner;
import com.azure.resourcemanager.azurestack.appservice.models.MigrateMySqlStatus;
import com.azure.resourcemanager.azurestack.appservice.models.OperationStatus;

public final class MigrateMySqlStatusImpl implements MigrateMySqlStatus {
    private MigrateMySqlStatusInner innerObject;

    private final com.azure.resourcemanager.azurestack.appservice.AppServiceManager serviceManager;

    MigrateMySqlStatusImpl(
        MigrateMySqlStatusInner innerObject,
        com.azure.resourcemanager.azurestack.appservice.AppServiceManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String id() {
        return this.innerModel().id();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String type() {
        return this.innerModel().type();
    }

    public String kind() {
        return this.innerModel().kind();
    }

    public OperationStatus migrationOperationStatus() {
        return this.innerModel().migrationOperationStatus();
    }

    public String operationId() {
        return this.innerModel().operationId();
    }

    public Boolean localMySqlEnabled() {
        return this.innerModel().localMySqlEnabled();
    }

    public MigrateMySqlStatusInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.azurestack.appservice.AppServiceManager manager() {
        return this.serviceManager;
    }
}
