// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azurestack.appservice.implementation;

import com.azure.resourcemanager.azurestack.appservice.fluent.models.PremierAddOnOfferInner;
import com.azure.resourcemanager.azurestack.appservice.models.AppServicePlanRestrictions;
import com.azure.resourcemanager.azurestack.appservice.models.PremierAddOnOffer;

public final class PremierAddOnOfferImpl implements PremierAddOnOffer {
    private PremierAddOnOfferInner innerObject;

    private final com.azure.resourcemanager.azurestack.appservice.AppServiceManager serviceManager;

    PremierAddOnOfferImpl(
        PremierAddOnOfferInner innerObject, com.azure.resourcemanager.azurestack.appservice.AppServiceManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String id() {
        return this.innerModel().id();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String type() {
        return this.innerModel().type();
    }

    public String kind() {
        return this.innerModel().kind();
    }

    public String sku() {
        return this.innerModel().sku();
    }

    public String product() {
        return this.innerModel().product();
    }

    public String vendor() {
        return this.innerModel().vendor();
    }

    public Boolean promoCodeRequired() {
        return this.innerModel().promoCodeRequired();
    }

    public Integer quota() {
        return this.innerModel().quota();
    }

    public AppServicePlanRestrictions webHostingPlanRestrictions() {
        return this.innerModel().webHostingPlanRestrictions();
    }

    public String privacyPolicyUrl() {
        return this.innerModel().privacyPolicyUrl();
    }

    public String legalTermsUrl() {
        return this.innerModel().legalTermsUrl();
    }

    public String marketplacePublisher() {
        return this.innerModel().marketplacePublisher();
    }

    public String marketplaceOffer() {
        return this.innerModel().marketplaceOffer();
    }

    public PremierAddOnOfferInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.azurestack.appservice.AppServiceManager manager() {
        return this.serviceManager;
    }
}
