// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azurestack.appservice.implementation;

import com.azure.resourcemanager.azurestack.appservice.fluent.models.SitePhpErrorLogFlagInner;
import com.azure.resourcemanager.azurestack.appservice.models.SitePhpErrorLogFlag;

public final class SitePhpErrorLogFlagImpl implements SitePhpErrorLogFlag {
    private SitePhpErrorLogFlagInner innerObject;

    private final com.azure.resourcemanager.azurestack.appservice.AppServiceManager serviceManager;

    SitePhpErrorLogFlagImpl(
        SitePhpErrorLogFlagInner innerObject,
        com.azure.resourcemanager.azurestack.appservice.AppServiceManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String id() {
        return this.innerModel().id();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String type() {
        return this.innerModel().type();
    }

    public String kind() {
        return this.innerModel().kind();
    }

    public String localLogErrors() {
        return this.innerModel().localLogErrors();
    }

    public String masterLogErrors() {
        return this.innerModel().masterLogErrors();
    }

    public String localLogErrorsMaxLength() {
        return this.innerModel().localLogErrorsMaxLength();
    }

    public String masterLogErrorsMaxLength() {
        return this.innerModel().masterLogErrorsMaxLength();
    }

    public SitePhpErrorLogFlagInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.azurestack.appservice.AppServiceManager manager() {
        return this.serviceManager;
    }
}
