// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.hybrid.iothub.implementation;

import com.azure.resourcemanager.hybrid.iothub.fluent.models.TestRouteResultInner;
import com.azure.resourcemanager.hybrid.iothub.models.TestResultStatus;
import com.azure.resourcemanager.hybrid.iothub.models.TestRouteResult;
import com.azure.resourcemanager.hybrid.iothub.models.TestRouteResultDetails;

public final class TestRouteResultImpl implements TestRouteResult {
    private TestRouteResultInner innerObject;

    private final com.azure.resourcemanager.hybrid.iothub.IotHubManager serviceManager;

    TestRouteResultImpl(
        TestRouteResultInner innerObject, com.azure.resourcemanager.hybrid.iothub.IotHubManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public TestResultStatus result() {
        return this.innerModel().result();
    }

    public TestRouteResultDetails details() {
        return this.innerModel().details();
    }

    public TestRouteResultInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.hybrid.iothub.IotHubManager manager() {
        return this.serviceManager;
    }
}
