// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azurestack.appservice.models;

import com.azure.resourcemanager.azurestack.appservice.fluent.models.ApplicationStackInner;
import java.util.List;

/** An immutable client-side representation of ApplicationStack. */
public interface ApplicationStack {
    /**
     * Gets the name property: Application stack name.
     *
     * @return the name value.
     */
    String name();

    /**
     * Gets the display property: Application stack display name.
     *
     * @return the display value.
     */
    String display();

    /**
     * Gets the dependency property: Application stack dependency.
     *
     * @return the dependency value.
     */
    String dependency();

    /**
     * Gets the majorVersions property: List of major versions available.
     *
     * @return the majorVersions value.
     */
    List<StackMajorVersion> majorVersions();

    /**
     * Gets the frameworks property: List of frameworks associated with application stack.
     *
     * @return the frameworks value.
     */
    List<ApplicationStack> frameworks();

    /**
     * Gets the inner com.azure.resourcemanager.azurestack.web.fluent.models.ApplicationStackInner object.
     *
     * @return the inner object.
     */
    ApplicationStackInner innerModel();
}
