// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azurestack.web.implementation;

import com.azure.resourcemanager.azurestack.web.fluent.models.AzureStoragePropertyDictionaryResourceInner;
import com.azure.resourcemanager.azurestack.web.models.AzureStorageInfoValue;
import com.azure.resourcemanager.azurestack.web.models.AzureStoragePropertyDictionaryResource;
import java.util.Collections;
import java.util.Map;

public final class AzureStoragePropertyDictionaryResourceImpl implements AzureStoragePropertyDictionaryResource {
    private AzureStoragePropertyDictionaryResourceInner innerObject;

    private final com.azure.resourcemanager.azurestack.web.AppServiceManager serviceManager;

    AzureStoragePropertyDictionaryResourceImpl(
        AzureStoragePropertyDictionaryResourceInner innerObject,
        com.azure.resourcemanager.azurestack.web.AppServiceManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String id() {
        return this.innerModel().id();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String type() {
        return this.innerModel().type();
    }

    public String kind() {
        return this.innerModel().kind();
    }

    public Map<String, AzureStorageInfoValue> properties() {
        Map<String, AzureStorageInfoValue> inner = this.innerModel().properties();
        if (inner != null) {
            return Collections.unmodifiableMap(inner);
        } else {
            return Collections.emptyMap();
        }
    }

    public AzureStoragePropertyDictionaryResourceInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.azurestack.web.AppServiceManager manager() {
        return this.serviceManager;
    }
}
