// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azurestack.web.implementation;

import com.azure.resourcemanager.azurestack.web.fluent.models.CustomHostnameAnalysisResultInner;
import com.azure.resourcemanager.azurestack.web.models.CustomHostnameAnalysisResult;
import com.azure.resourcemanager.azurestack.web.models.DnsVerificationTestResult;
import com.azure.resourcemanager.azurestack.web.models.ErrorEntity;
import java.util.Collections;
import java.util.List;

public final class CustomHostnameAnalysisResultImpl implements CustomHostnameAnalysisResult {
    private CustomHostnameAnalysisResultInner innerObject;

    private final com.azure.resourcemanager.azurestack.web.AppServiceManager serviceManager;

    CustomHostnameAnalysisResultImpl(
        CustomHostnameAnalysisResultInner innerObject,
        com.azure.resourcemanager.azurestack.web.AppServiceManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String id() {
        return this.innerModel().id();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String type() {
        return this.innerModel().type();
    }

    public String kind() {
        return this.innerModel().kind();
    }

    public Boolean isHostnameAlreadyVerified() {
        return this.innerModel().isHostnameAlreadyVerified();
    }

    public DnsVerificationTestResult customDomainVerificationTest() {
        return this.innerModel().customDomainVerificationTest();
    }

    public ErrorEntity customDomainVerificationFailureInfo() {
        return this.innerModel().customDomainVerificationFailureInfo();
    }

    public Boolean hasConflictOnScaleUnit() {
        return this.innerModel().hasConflictOnScaleUnit();
    }

    public Boolean hasConflictAcrossSubscription() {
        return this.innerModel().hasConflictAcrossSubscription();
    }

    public String conflictingAppResourceId() {
        return this.innerModel().conflictingAppResourceId();
    }

    public List<String> cNameRecords() {
        List<String> inner = this.innerModel().cNameRecords();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public List<String> txtRecords() {
        List<String> inner = this.innerModel().txtRecords();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public List<String> aRecords() {
        List<String> inner = this.innerModel().aRecords();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public List<String> alternateCNameRecords() {
        List<String> inner = this.innerModel().alternateCNameRecords();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public List<String> alternateTxtRecords() {
        List<String> inner = this.innerModel().alternateTxtRecords();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public CustomHostnameAnalysisResultInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.azurestack.web.AppServiceManager manager() {
        return this.serviceManager;
    }
}
