// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azurestack.web.implementation;

import com.azure.resourcemanager.azurestack.web.fluent.models.NetworkTraceInner;
import com.azure.resourcemanager.azurestack.web.models.NetworkTrace;

public final class NetworkTraceImpl implements NetworkTrace {
    private NetworkTraceInner innerObject;

    private final com.azure.resourcemanager.azurestack.web.AppServiceManager serviceManager;

    NetworkTraceImpl(
        NetworkTraceInner innerObject, com.azure.resourcemanager.azurestack.web.AppServiceManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String path() {
        return this.innerModel().path();
    }

    public String status() {
        return this.innerModel().status();
    }

    public String message() {
        return this.innerModel().message();
    }

    public NetworkTraceInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.azurestack.web.AppServiceManager manager() {
        return this.serviceManager;
    }
}
