// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azurestack.web.implementation;

import com.azure.resourcemanager.azurestack.web.fluent.models.PerfMonResponseInner;
import com.azure.resourcemanager.azurestack.web.models.PerfMonResponse;
import com.azure.resourcemanager.azurestack.web.models.PerfMonSet;

public final class PerfMonResponseImpl implements PerfMonResponse {
    private PerfMonResponseInner innerObject;

    private final com.azure.resourcemanager.azurestack.web.AppServiceManager serviceManager;

    PerfMonResponseImpl(
        PerfMonResponseInner innerObject, com.azure.resourcemanager.azurestack.web.AppServiceManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String code() {
        return this.innerModel().code();
    }

    public String message() {
        return this.innerModel().message();
    }

    public PerfMonSet data() {
        return this.innerModel().data();
    }

    public PerfMonResponseInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.azurestack.web.AppServiceManager manager() {
        return this.serviceManager;
    }
}
