// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azurestack.web.implementation;

import com.azure.resourcemanager.azurestack.web.fluent.models.TriggeredJobHistoryInner;
import com.azure.resourcemanager.azurestack.web.models.TriggeredJobHistory;
import com.azure.resourcemanager.azurestack.web.models.TriggeredJobRun;
import java.util.Collections;
import java.util.List;

public final class TriggeredJobHistoryImpl implements TriggeredJobHistory {
    private TriggeredJobHistoryInner innerObject;

    private final com.azure.resourcemanager.azurestack.web.AppServiceManager serviceManager;

    TriggeredJobHistoryImpl(
        TriggeredJobHistoryInner innerObject,
        com.azure.resourcemanager.azurestack.web.AppServiceManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String id() {
        return this.innerModel().id();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String type() {
        return this.innerModel().type();
    }

    public String kind() {
        return this.innerModel().kind();
    }

    public List<TriggeredJobRun> runs() {
        List<TriggeredJobRun> inner = this.innerModel().runs();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public TriggeredJobHistoryInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.azurestack.web.AppServiceManager manager() {
        return this.serviceManager;
    }
}
