// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.hybrid.network.models;

import com.azure.resourcemanager.hybrid.network.fluent.models.BgpPeerStatusListResultInner;
import java.util.List;

/** An immutable client-side representation of BgpPeerStatusListResult. */
public interface BgpPeerStatusListResult {
    /**
     * Gets the value property: List of BGP peers.
     *
     * @return the value value.
     */
    List<BgpPeerStatus> value();

    /**
     * Gets the inner com.azure.resourcemanager.azurestack.network.fluent.models.BgpPeerStatusListResultInner object.
     *
     * @return the inner object.
     */
    BgpPeerStatusListResultInner innerModel();
}
