// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.hybrid.network.models;

import com.azure.resourcemanager.hybrid.network.fluent.models.InterfaceEndpointInner;
import java.util.List;
import java.util.Map;

/** An immutable client-side representation of InterfaceEndpoint. */
public interface InterfaceEndpoint {
    /**
     * Gets the name property: The name of the resource.
     *
     * @return the name value.
     */
    String name();

    /**
     * Gets the type property: The type of the resource.
     *
     * @return the type value.
     */
    String type();

    /**
     * Gets the location property: The geo-location where the resource lives.
     *
     * @return the location value.
     */
    String location();

    /**
     * Gets the tags property: Resource tags.
     *
     * @return the tags value.
     */
    Map<String, String> tags();

    /**
     * Gets the etag property: Gets a unique read-only string that changes whenever the resource is updated.
     *
     * @return the etag value.
     */
    String etag();

    /**
     * Gets the fqdn property: A first-party service's FQDN that is mapped to the private IP allocated via this
     * interface endpoint.
     *
     * @return the fqdn value.
     */
    String fqdn();

    /**
     * Gets the endpointService property: A reference to the service being brought into the virtual network.
     *
     * @return the endpointService value.
     */
    EndpointService endpointService();

    /**
     * Gets the subnet property: The ID of the subnet from which the private IP will be allocated.
     *
     * @return the subnet value.
     */
    Subnet subnet();

    /**
     * Gets the networkInterfaces property: Gets an array of references to the network interfaces created for this
     * interface endpoint.
     *
     * @return the networkInterfaces value.
     */
    List<NetworkInterface> networkInterfaces();

    /**
     * Gets the owner property: A read-only property that identifies who created this interface endpoint.
     *
     * @return the owner value.
     */
    String owner();

    /**
     * Gets the provisioningState property: The provisioning state of the interface endpoint. Possible values are:
     * 'Updating', 'Deleting', and 'Failed'.
     *
     * @return the provisioningState value.
     */
    String provisioningState();

    /**
     * Gets the id property: Resource ID.
     *
     * @return the id value.
     */
    String id();

    /**
     * Gets the inner com.azure.resourcemanager.azurestack.network.fluent.models.InterfaceEndpointInner object.
     *
     * @return the inner object.
     */
    InterfaceEndpointInner innerModel();
}
