// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azurestack.resources.implementation;

import com.azure.resourcemanager.azurestack.resources.fluent.models.CheckResourceNameResultInner;
import com.azure.resourcemanager.azurestack.resources.models.CheckResourceNameResult;
import com.azure.resourcemanager.azurestack.resources.models.ResourceNameStatus;

public final class CheckResourceNameResultImpl implements CheckResourceNameResult {
    private CheckResourceNameResultInner innerObject;

    private final com.azure.resourcemanager.azurestack.resources.ResourceManager serviceManager;

    CheckResourceNameResultImpl(
        CheckResourceNameResultInner innerObject,
        com.azure.resourcemanager.azurestack.resources.ResourceManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String name() {
        return this.innerModel().name();
    }

    public String type() {
        return this.innerModel().type();
    }

    public ResourceNameStatus status() {
        return this.innerModel().status();
    }

    public CheckResourceNameResultInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.azurestack.resources.ResourceManager manager() {
        return this.serviceManager;
    }
}
