// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azurestack.resources.implementation;

import com.azure.core.management.exception.ManagementError;
import com.azure.resourcemanager.azurestack.resources.fluent.models.DeploymentValidateResultInner;
import com.azure.resourcemanager.azurestack.resources.models.DeploymentPropertiesExtended;
import com.azure.resourcemanager.azurestack.resources.models.DeploymentValidateResult;

public final class DeploymentValidateResultImpl implements DeploymentValidateResult {
    private DeploymentValidateResultInner innerObject;

    private final com.azure.resourcemanager.azurestack.resources.ResourceManager serviceManager;

    DeploymentValidateResultImpl(
        DeploymentValidateResultInner innerObject,
        com.azure.resourcemanager.azurestack.resources.ResourceManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public ManagementError error() {
        return this.innerModel().error();
    }

    public DeploymentPropertiesExtended properties() {
        return this.innerModel().properties();
    }

    public DeploymentValidateResultInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.azurestack.resources.ResourceManager manager() {
        return this.serviceManager;
    }
}
