// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azurestack.resources.implementation;

import com.azure.core.management.exception.ManagementError;
import com.azure.resourcemanager.azurestack.resources.fluent.models.ResourceGroupExportResultInner;
import com.azure.resourcemanager.azurestack.resources.models.ResourceGroupExportResult;

public final class ResourceGroupExportResultImpl implements ResourceGroupExportResult {
    private ResourceGroupExportResultInner innerObject;

    private final com.azure.resourcemanager.azurestack.resources.ResourceManager serviceManager;

    ResourceGroupExportResultImpl(
        ResourceGroupExportResultInner innerObject,
        com.azure.resourcemanager.azurestack.resources.ResourceManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public Object template() {
        return this.innerModel().template();
    }

    public ManagementError error() {
        return this.innerModel().error();
    }

    public ResourceGroupExportResultInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.azurestack.resources.ResourceManager manager() {
        return this.serviceManager;
    }
}
