// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azurestack.resources.implementation;

import com.azure.resourcemanager.azurestack.resources.fluent.models.TagValueInner;
import com.azure.resourcemanager.azurestack.resources.models.TagCount;
import com.azure.resourcemanager.azurestack.resources.models.TagValue;

public final class TagValueImpl implements TagValue {
    private TagValueInner innerObject;

    private final com.azure.resourcemanager.azurestack.resources.ResourceManager serviceManager;

    TagValueImpl(
        TagValueInner innerObject, com.azure.resourcemanager.azurestack.resources.ResourceManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String id() {
        return this.innerModel().id();
    }

    public String tagValue() {
        return this.innerModel().tagValue();
    }

    public TagCount count() {
        return this.innerModel().count();
    }

    public TagValueInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.azurestack.resources.ResourceManager manager() {
        return this.serviceManager;
    }
}
