// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azurestack.resources.implementation;

import com.azure.core.http.rest.PagedIterable;
import com.azure.core.util.Context;
import com.azure.core.util.logging.ClientLogger;
import com.azure.resourcemanager.azurestack.resources.fluent.TenantsClient;
import com.azure.resourcemanager.azurestack.resources.fluent.models.TenantIdDescriptionInner;
import com.azure.resourcemanager.azurestack.resources.models.TenantIdDescription;
import com.azure.resourcemanager.azurestack.resources.models.Tenants;
import com.fasterxml.jackson.annotation.JsonIgnore;

public final class TenantsImpl implements Tenants {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(TenantsImpl.class);

    private final TenantsClient innerClient;

    private final com.azure.resourcemanager.azurestack.resources.ResourceManager serviceManager;

    public TenantsImpl(
        TenantsClient innerClient, com.azure.resourcemanager.azurestack.resources.ResourceManager serviceManager) {
        this.innerClient = innerClient;
        this.serviceManager = serviceManager;
    }

    public PagedIterable<TenantIdDescription> list() {
        PagedIterable<TenantIdDescriptionInner> inner = this.serviceClient().list();
        return Utils.mapPage(inner, inner1 -> new TenantIdDescriptionImpl(inner1, this.manager()));
    }

    public PagedIterable<TenantIdDescription> list(Context context) {
        PagedIterable<TenantIdDescriptionInner> inner = this.serviceClient().list(context);
        return Utils.mapPage(inner, inner1 -> new TenantIdDescriptionImpl(inner1, this.manager()));
    }

    private TenantsClient serviceClient() {
        return this.innerClient;
    }

    private com.azure.resourcemanager.azurestack.resources.ResourceManager manager() {
        return this.serviceManager;
    }
}
