// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azurestack.network.implementation;

import com.azure.resourcemanager.azurestack.network.fluent.models.BgpPeerStatusListResultInner;
import com.azure.resourcemanager.azurestack.network.models.BgpPeerStatus;
import com.azure.resourcemanager.azurestack.network.models.BgpPeerStatusListResult;
import java.util.Collections;
import java.util.List;

public final class BgpPeerStatusListResultImpl implements BgpPeerStatusListResult {
    private BgpPeerStatusListResultInner innerObject;

    private final com.azure.resourcemanager.azurestack.network.NetworkManager serviceManager;

    BgpPeerStatusListResultImpl(
        BgpPeerStatusListResultInner innerObject,
        com.azure.resourcemanager.azurestack.network.NetworkManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public List<BgpPeerStatus> value() {
        List<BgpPeerStatus> inner = this.innerModel().value();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public BgpPeerStatusListResultInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.azurestack.network.NetworkManager manager() {
        return this.serviceManager;
    }
}
