// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azurestack.network.implementation;

import com.azure.core.http.rest.PagedIterable;
import com.azure.core.http.rest.Response;
import com.azure.core.http.rest.SimpleResponse;
import com.azure.core.util.Context;
import com.azure.core.util.logging.ClientLogger;
import com.azure.resourcemanager.azurestack.network.fluent.SecurityRulesClient;
import com.azure.resourcemanager.azurestack.network.fluent.models.SecurityRuleInner;
import com.azure.resourcemanager.azurestack.network.models.SecurityRule;
import com.azure.resourcemanager.azurestack.network.models.SecurityRules;
import com.fasterxml.jackson.annotation.JsonIgnore;

public final class SecurityRulesImpl implements SecurityRules {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(SecurityRulesImpl.class);

    private final SecurityRulesClient innerClient;

    private final com.azure.resourcemanager.azurestack.network.NetworkManager serviceManager;

    public SecurityRulesImpl(
        SecurityRulesClient innerClient, com.azure.resourcemanager.azurestack.network.NetworkManager serviceManager) {
        this.innerClient = innerClient;
        this.serviceManager = serviceManager;
    }

    public void delete(String resourceGroupName, String networkSecurityGroupName, String securityRuleName) {
        this.serviceClient().delete(resourceGroupName, networkSecurityGroupName, securityRuleName);
    }

    public void delete(
        String resourceGroupName, String networkSecurityGroupName, String securityRuleName, Context context) {
        this.serviceClient().delete(resourceGroupName, networkSecurityGroupName, securityRuleName, context);
    }

    public SecurityRule get(String resourceGroupName, String networkSecurityGroupName, String securityRuleName) {
        SecurityRuleInner inner =
            this.serviceClient().get(resourceGroupName, networkSecurityGroupName, securityRuleName);
        if (inner != null) {
            return new SecurityRuleImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    public Response<SecurityRule> getWithResponse(
        String resourceGroupName, String networkSecurityGroupName, String securityRuleName, Context context) {
        Response<SecurityRuleInner> inner =
            this
                .serviceClient()
                .getWithResponse(resourceGroupName, networkSecurityGroupName, securityRuleName, context);
        if (inner != null) {
            return new SimpleResponse<>(
                inner.getRequest(),
                inner.getStatusCode(),
                inner.getHeaders(),
                new SecurityRuleImpl(inner.getValue(), this.manager()));
        } else {
            return null;
        }
    }

    public SecurityRule createOrUpdate(
        String resourceGroupName,
        String networkSecurityGroupName,
        String securityRuleName,
        SecurityRuleInner securityRuleParameters) {
        SecurityRuleInner inner =
            this
                .serviceClient()
                .createOrUpdate(resourceGroupName, networkSecurityGroupName, securityRuleName, securityRuleParameters);
        if (inner != null) {
            return new SecurityRuleImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    public SecurityRule createOrUpdate(
        String resourceGroupName,
        String networkSecurityGroupName,
        String securityRuleName,
        SecurityRuleInner securityRuleParameters,
        Context context) {
        SecurityRuleInner inner =
            this
                .serviceClient()
                .createOrUpdate(
                    resourceGroupName, networkSecurityGroupName, securityRuleName, securityRuleParameters, context);
        if (inner != null) {
            return new SecurityRuleImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    public PagedIterable<SecurityRule> list(String resourceGroupName, String networkSecurityGroupName) {
        PagedIterable<SecurityRuleInner> inner = this.serviceClient().list(resourceGroupName, networkSecurityGroupName);
        return Utils.mapPage(inner, inner1 -> new SecurityRuleImpl(inner1, this.manager()));
    }

    public PagedIterable<SecurityRule> list(
        String resourceGroupName, String networkSecurityGroupName, Context context) {
        PagedIterable<SecurityRuleInner> inner =
            this.serviceClient().list(resourceGroupName, networkSecurityGroupName, context);
        return Utils.mapPage(inner, inner1 -> new SecurityRuleImpl(inner1, this.manager()));
    }

    private SecurityRulesClient serviceClient() {
        return this.innerClient;
    }

    private com.azure.resourcemanager.azurestack.network.NetworkManager manager() {
        return this.serviceManager;
    }
}
