// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azurestack.web.models;

import com.azure.resourcemanager.azurestack.web.fluent.models.CapabilityInner;

/** An immutable client-side representation of Capability. */
public interface Capability {
    /**
     * Gets the name property: Name of the SKU capability.
     *
     * @return the name value.
     */
    String name();

    /**
     * Gets the value property: Value of the SKU capability.
     *
     * @return the value value.
     */
    String value();

    /**
     * Gets the reason property: Reason of the SKU capability.
     *
     * @return the reason value.
     */
    String reason();

    /**
     * Gets the inner com.azure.resourcemanager.azurestack.web.fluent.models.CapabilityInner object.
     *
     * @return the inner object.
     */
    CapabilityInner innerModel();
}
