// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azurestack.keyvault.implementation;

import com.azure.resourcemanager.azurestack.keyvault.fluent.models.OperationInner;
import com.azure.resourcemanager.azurestack.keyvault.models.Operation;
import com.azure.resourcemanager.azurestack.keyvault.models.OperationDisplay;
import com.azure.resourcemanager.azurestack.keyvault.models.ServiceSpecification;

public final class OperationImpl implements Operation {
    private OperationInner innerObject;

    private final com.azure.resourcemanager.azurestack.keyvault.KeyVaultManager serviceManager;

    OperationImpl(
        OperationInner innerObject, com.azure.resourcemanager.azurestack.keyvault.KeyVaultManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String name() {
        return this.innerModel().name();
    }

    public OperationDisplay display() {
        return this.innerModel().display();
    }

    public String origin() {
        return this.innerModel().origin();
    }

    public Boolean isDataAction() {
        return this.innerModel().isDataAction();
    }

    public ServiceSpecification serviceSpecification() {
        return this.innerModel().serviceSpecification();
    }

    public OperationInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.azurestack.keyvault.KeyVaultManager manager() {
        return this.serviceManager;
    }
}
