// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.hybrid.resources.implementation;

import com.azure.resourcemanager.hybrid.resources.fluent.models.DeploymentOperationInner;
import com.azure.resourcemanager.hybrid.resources.models.DeploymentOperation;
import com.azure.resourcemanager.hybrid.resources.models.DeploymentOperationProperties;

public final class DeploymentOperationImpl implements DeploymentOperation {
    private DeploymentOperationInner innerObject;

    private final com.azure.resourcemanager.hybrid.resources.ResourceManager serviceManager;

    DeploymentOperationImpl(
        DeploymentOperationInner innerObject,
        com.azure.resourcemanager.hybrid.resources.ResourceManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String id() {
        return this.innerModel().id();
    }

    public String operationId() {
        return this.innerModel().operationId();
    }

    public DeploymentOperationProperties properties() {
        return this.innerModel().properties();
    }

    public DeploymentOperationInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.hybrid.resources.ResourceManager manager() {
        return this.serviceManager;
    }
}
