// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.hybrid.resources.implementation;

import com.azure.core.http.rest.Response;
import com.azure.core.http.rest.SimpleResponse;
import com.azure.core.util.Context;
import com.azure.core.util.logging.ClientLogger;
import com.azure.resourcemanager.hybrid.resources.fluent.ResourceProvidersClient;
import com.azure.resourcemanager.hybrid.resources.fluent.models.CheckResourceNameResultInner;
import com.azure.resourcemanager.hybrid.resources.models.CheckResourceNameResult;
import com.azure.resourcemanager.hybrid.resources.models.ResourceName;
import com.azure.resourcemanager.hybrid.resources.models.ResourceProviders;
import com.fasterxml.jackson.annotation.JsonIgnore;

public final class ResourceProvidersImpl implements ResourceProviders {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(ResourceProvidersImpl.class);

    private final ResourceProvidersClient innerClient;

    private final com.azure.resourcemanager.hybrid.resources.ResourceManager serviceManager;

    public ResourceProvidersImpl(
        ResourceProvidersClient innerClient,
        com.azure.resourcemanager.hybrid.resources.ResourceManager serviceManager) {
        this.innerClient = innerClient;
        this.serviceManager = serviceManager;
    }

    public CheckResourceNameResult checkResourceName() {
        CheckResourceNameResultInner inner = this.serviceClient().checkResourceName();
        if (inner != null) {
            return new CheckResourceNameResultImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    public Response<CheckResourceNameResult> checkResourceNameWithResponse(
        ResourceName resourceNameDefinition, Context context) {
        Response<CheckResourceNameResultInner> inner =
            this.serviceClient().checkResourceNameWithResponse(resourceNameDefinition, context);
        if (inner != null) {
            return new SimpleResponse<>(
                inner.getRequest(),
                inner.getStatusCode(),
                inner.getHeaders(),
                new CheckResourceNameResultImpl(inner.getValue(), this.manager()));
        } else {
            return null;
        }
    }

    private ResourceProvidersClient serviceClient() {
        return this.innerClient;
    }

    private com.azure.resourcemanager.hybrid.resources.ResourceManager manager() {
        return this.serviceManager;
    }
}
