// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.hybrid.resources.implementation;

import com.azure.resourcemanager.hybrid.resources.fluent.models.SubscriptionInner;
import com.azure.resourcemanager.hybrid.resources.models.Subscription;
import com.azure.resourcemanager.hybrid.resources.models.SubscriptionPolicies;
import com.azure.resourcemanager.hybrid.resources.models.SubscriptionState;

public final class SubscriptionImpl implements Subscription {
    private SubscriptionInner innerObject;

    private final com.azure.resourcemanager.hybrid.resources.ResourceManager serviceManager;

    SubscriptionImpl(
        SubscriptionInner innerObject, com.azure.resourcemanager.hybrid.resources.ResourceManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String id() {
        return this.innerModel().id();
    }

    public String subscriptionId() {
        return this.innerModel().subscriptionId();
    }

    public String displayName() {
        return this.innerModel().displayName();
    }

    public SubscriptionState state() {
        return this.innerModel().state();
    }

    public SubscriptionPolicies subscriptionPolicies() {
        return this.innerModel().subscriptionPolicies();
    }

    public String authorizationSource() {
        return this.innerModel().authorizationSource();
    }

    public SubscriptionInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.hybrid.resources.ResourceManager manager() {
        return this.serviceManager;
    }
}
