// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azurestack.eventhubs.implementation;

import com.azure.core.http.rest.PagedIterable;
import com.azure.core.util.Context;
import com.azure.core.util.logging.ClientLogger;
import com.azure.resourcemanager.azurestack.eventhubs.fluent.RegionsClient;
import com.azure.resourcemanager.azurestack.eventhubs.fluent.models.MessagingRegionsInner;
import com.azure.resourcemanager.azurestack.eventhubs.models.MessagingRegions;
import com.azure.resourcemanager.azurestack.eventhubs.models.Regions;
import com.fasterxml.jackson.annotation.JsonIgnore;

public final class RegionsImpl implements Regions {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(RegionsImpl.class);

    private final RegionsClient innerClient;

    private final com.azure.resourcemanager.azurestack.eventhubs.EventHubsManager serviceManager;

    public RegionsImpl(
        RegionsClient innerClient, com.azure.resourcemanager.azurestack.eventhubs.EventHubsManager serviceManager) {
        this.innerClient = innerClient;
        this.serviceManager = serviceManager;
    }

    public PagedIterable<MessagingRegions> listBySku(String sku) {
        PagedIterable<MessagingRegionsInner> inner = this.serviceClient().listBySku(sku);
        return Utils.mapPage(inner, inner1 -> new MessagingRegionsImpl(inner1, this.manager()));
    }

    public PagedIterable<MessagingRegions> listBySku(String sku, Context context) {
        PagedIterable<MessagingRegionsInner> inner = this.serviceClient().listBySku(sku, context);
        return Utils.mapPage(inner, inner1 -> new MessagingRegionsImpl(inner1, this.manager()));
    }

    private RegionsClient serviceClient() {
        return this.innerClient;
    }

    private com.azure.resourcemanager.azurestack.eventhubs.EventHubsManager manager() {
        return this.serviceManager;
    }
}
