// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azurestack.storage.implementation;

import com.azure.resourcemanager.azurestack.storage.fluent.models.BlobRestoreStatusInner;
import com.azure.resourcemanager.azurestack.storage.models.BlobRestoreParameters;
import com.azure.resourcemanager.azurestack.storage.models.BlobRestoreProgressStatus;
import com.azure.resourcemanager.azurestack.storage.models.BlobRestoreStatus;

public final class BlobRestoreStatusImpl implements BlobRestoreStatus {
    private BlobRestoreStatusInner innerObject;

    private final com.azure.resourcemanager.azurestack.storage.StorageManager serviceManager;

    BlobRestoreStatusImpl(
        BlobRestoreStatusInner innerObject,
        com.azure.resourcemanager.azurestack.storage.StorageManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public BlobRestoreProgressStatus status() {
        return this.innerModel().status();
    }

    public String failureReason() {
        return this.innerModel().failureReason();
    }

    public String restoreId() {
        return this.innerModel().restoreId();
    }

    public BlobRestoreParameters parameters() {
        return this.innerModel().parameters();
    }

    public BlobRestoreStatusInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.azurestack.storage.StorageManager manager() {
        return this.serviceManager;
    }
}
