// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azurestack.storage.implementation;

import com.azure.resourcemanager.azurestack.storage.fluent.models.ListAccountSasResponseInner;
import com.azure.resourcemanager.azurestack.storage.models.ListAccountSasResponse;

public final class ListAccountSasResponseImpl implements ListAccountSasResponse {
    private ListAccountSasResponseInner innerObject;

    private final com.azure.resourcemanager.azurestack.storage.StorageManager serviceManager;

    ListAccountSasResponseImpl(
        ListAccountSasResponseInner innerObject,
        com.azure.resourcemanager.azurestack.storage.StorageManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String accountSasToken() {
        return this.innerModel().accountSasToken();
    }

    public ListAccountSasResponseInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.azurestack.storage.StorageManager manager() {
        return this.serviceManager;
    }
}
