// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azurestack.storage.implementation;

import com.azure.resourcemanager.azurestack.storage.fluent.models.SkuInformationInner;
import com.azure.resourcemanager.azurestack.storage.models.Kind;
import com.azure.resourcemanager.azurestack.storage.models.Restriction;
import com.azure.resourcemanager.azurestack.storage.models.SkuCapability;
import com.azure.resourcemanager.azurestack.storage.models.SkuInformation;
import com.azure.resourcemanager.azurestack.storage.models.SkuName;
import com.azure.resourcemanager.azurestack.storage.models.SkuTier;
import java.util.Collections;
import java.util.List;

public final class SkuInformationImpl implements SkuInformation {
    private SkuInformationInner innerObject;

    private final com.azure.resourcemanager.azurestack.storage.StorageManager serviceManager;

    SkuInformationImpl(
        SkuInformationInner innerObject, com.azure.resourcemanager.azurestack.storage.StorageManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public SkuName name() {
        return this.innerModel().name();
    }

    public SkuTier tier() {
        return this.innerModel().tier();
    }

    public String resourceType() {
        return this.innerModel().resourceType();
    }

    public Kind kind() {
        return this.innerModel().kind();
    }

    public List<String> locations() {
        List<String> inner = this.innerModel().locations();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public List<SkuCapability> capabilities() {
        List<SkuCapability> inner = this.innerModel().capabilities();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public List<Restriction> restrictions() {
        List<Restriction> inner = this.innerModel().restrictions();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public SkuInformationInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.azurestack.storage.StorageManager manager() {
        return this.serviceManager;
    }
}
