// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.azurestack.storage.implementation;

import com.azure.resourcemanager.azurestack.storage.fluent.models.UsageInner;
import com.azure.resourcemanager.azurestack.storage.models.Usage;
import com.azure.resourcemanager.azurestack.storage.models.UsageName;
import com.azure.resourcemanager.azurestack.storage.models.UsageUnit;

public final class UsageImpl implements Usage {
    private UsageInner innerObject;

    private final com.azure.resourcemanager.azurestack.storage.StorageManager serviceManager;

    UsageImpl(UsageInner innerObject, com.azure.resourcemanager.azurestack.storage.StorageManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public UsageUnit unit() {
        return this.innerModel().unit();
    }

    public Integer currentValue() {
        return this.innerModel().currentValue();
    }

    public Integer limit() {
        return this.innerModel().limit();
    }

    public UsageName name() {
        return this.innerModel().name();
    }

    public UsageInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.azurestack.storage.StorageManager manager() {
        return this.serviceManager;
    }
}
