// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.hybrid.eventhubs.implementation;

import com.azure.resourcemanager.hybrid.eventhubs.fluent.models.EHNamespaceIdListResultInner;
import com.azure.resourcemanager.hybrid.eventhubs.models.EHNamespaceIdContainer;
import com.azure.resourcemanager.hybrid.eventhubs.models.EHNamespaceIdListResult;
import java.util.Collections;
import java.util.List;

public final class EHNamespaceIdListResultImpl implements EHNamespaceIdListResult {
    private EHNamespaceIdListResultInner innerObject;

    private final com.azure.resourcemanager.hybrid.eventhubs.EventHubsManager serviceManager;

    EHNamespaceIdListResultImpl(
        EHNamespaceIdListResultInner innerObject,
        com.azure.resourcemanager.hybrid.eventhubs.EventHubsManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public List<EHNamespaceIdContainer> value() {
        List<EHNamespaceIdContainer> inner = this.innerModel().value();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public EHNamespaceIdListResultInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.hybrid.eventhubs.EventHubsManager manager() {
        return this.serviceManager;
    }
}
