// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.hybrid.eventhubs.implementation;

import com.azure.resourcemanager.hybrid.eventhubs.fluent.models.PrivateLinkResourcesListResultInner;
import com.azure.resourcemanager.hybrid.eventhubs.models.PrivateLinkResource;
import com.azure.resourcemanager.hybrid.eventhubs.models.PrivateLinkResourcesListResult;
import java.util.Collections;
import java.util.List;

public final class PrivateLinkResourcesListResultImpl implements PrivateLinkResourcesListResult {
    private PrivateLinkResourcesListResultInner innerObject;

    private final com.azure.resourcemanager.hybrid.eventhubs.EventHubsManager serviceManager;

    PrivateLinkResourcesListResultImpl(
        PrivateLinkResourcesListResultInner innerObject,
        com.azure.resourcemanager.hybrid.eventhubs.EventHubsManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public List<PrivateLinkResource> value() {
        List<PrivateLinkResource> inner = this.innerModel().value();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public String nextLink() {
        return this.innerModel().nextLink();
    }

    public PrivateLinkResourcesListResultInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.hybrid.eventhubs.EventHubsManager manager() {
        return this.serviceManager;
    }
}
